import React, { useState, useEffect } from 'react';
import {
  View, Text, StyleSheet, ScrollView,
  TouchableOpacity, StatusBar, ActivityIndicator,
} from 'react-native';
import LinearGradient from 'react-native-linear-gradient';
import Video from 'react-native-video';
import { Colors, Typography, Spacing, Radius, Shadow } from '../../theme';
import SenseCard from '../../components/common/SenseCard';
import { useApp } from '../../utils/AppContext';
import { generateDailySummary } from '../../services/NovaService';
import BunnieIcon from '../../components/common/BunnieIcon';

export default function CaregiverScreen({ navigation }) {
  const { state } = useApp();
  const [summary, setSummary]   = useState(null);
  const [mp3Uri, setMp3Uri] = useState(null);
  const [loading, setLoading]   = useState(true);
  const [lastUpdated, setLastUpdated] = useState(null);
  const [summaryLoaded, setSummaryLoaded] = useState(0);

  useEffect(() => { fetchSummary(); }, []);

  const fetchSummary = async () => {
    setLoading(true);
    try {
      const s = await generateDailySummary({
        name:          state.user.name || 'the user',
        conversations: state.user.totalConversations,
        alerts:        state.soundAlerts.length,
        milestones:    state.user.milestones.map(m => m.title || m),
      });
      setSummary(s);
      setLastUpdated(new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }));
      setSummaryLoaded(t => t + 1);
    } catch (e) {
      console.error('Caregiver summary failed:', e);
      // Only use fallback if Nova completely fails
      setSummary({
        summary: `${state.user.name || 'The user'} completed ${state.user.totalConversations} conversations today and earned ${state.user.xpPoints} XP.`,
        highlights: [
          `${state.user.totalConversations} conversations completed`,
          `${state.soundAlerts.length} sound alerts detected`,
          `Level ${state.user.level} achieved`,
        ],
        mood: 'positive',
        independenceScore: Math.min(100, 50 + state.user.totalConversations * 5),
      });
    } finally {
      setLoading(false);
    }
  };

  const scoreColor = (score) => {
    if (score >= 70) return Colors.success;
    if (score >= 40) return Colors.warning;
    return Colors.error;
  };

  return (
    <View style={{ flex: 1, backgroundColor: Colors.background }}>
      <StatusBar barStyle="light-content" />

      <LinearGradient colors={['#4A148C', '#7B1FA2']} style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.back}>
          <Text style={{ fontSize: 22, color: '#fff' }}>←</Text>
        </TouchableOpacity>
        <View style={{ flex: 1 }}>
          <Text style={[Typography.titleLarge, { color: '#fff' }]}>💙 Caregiver View</Text>
          <Text style={[Typography.bodySmall, { color: 'rgba(255,255,255,0.75)' }]}>
            {state.user.name || 'User'}'s day at a glance · Bunnie AI
          </Text>
        </View>
        <TouchableOpacity onPress={fetchSummary} disabled={loading} style={styles.refreshBtn}>
          <Text style={{ fontSize: 18 }}>{loading ? '⏳' : '🔄'}</Text>
        </TouchableOpacity>
      </LinearGradient>

      {loading ? (
        <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', gap: Spacing.md }}>
          <ActivityIndicator size="large" color={Colors.primary} />
          <Text style={[Typography.bodyMedium, { color: Colors.subtitle }]}>
            Bunnie is generating today's summary…
          </Text>
        </View>
      ) : (
        <ScrollView contentContainerStyle={{ padding: Spacing.md, gap: Spacing.md, paddingBottom: 40 }}>

          {/* Last updated */}
          {lastUpdated && (
            <View style={{ flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', gap: 6 }}>
              <BunnieIcon size={14} animation="pop" trigger={summaryLoaded} />
              <Text style={[Typography.labelSmall, { color: Colors.subtitle }]}>Generated by Bunnie · {lastUpdated}</Text>
            </View>
          )}

          {/* Independence Score */}
          <SenseCard variant="elevated" padding="xl">
            <Text style={[Typography.labelMedium, { color: Colors.subtitle, textAlign: 'center', marginBottom: Spacing.sm }]}>
              INDEPENDENCE SCORE TODAY
            </Text>
            <View style={{ alignItems: 'center' }}>
              <View style={[styles.scoreCircle, { borderColor: scoreColor(summary.independenceScore) }]}>
                <Text style={[Typography.displayMedium, { color: scoreColor(summary.independenceScore), fontWeight: '800' }]}>
                  {summary.independenceScore}
                </Text>
                <Text style={[Typography.bodySmall, { color: Colors.subtitle }]}>/ 100</Text>
              </View>
            </View>
            <Text style={[Typography.bodyMedium, { color: Colors.onSurfaceVariant, textAlign: 'center', marginTop: Spacing.md }]}>
              {summary.independenceScore >= 70
                ? '🌟 Exceptional independence today!'
                : summary.independenceScore >= 40
                ? '👍 Good progress — keep it up!'
                : '💪 Keep supporting their journey'}
            </Text>
          </SenseCard>

          {/* Daily Summary — Bunnie generated */}
          <SenseCard variant="tonal" padding="md">
            <View style={{ flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, marginBottom: Spacing.sm }}>
              <Text style={[Typography.labelSmall, { color: Colors.primary }]}>TODAY'S SUMMARY</Text>
              <View style={styles.novaTag}>
                <Text style={{ color: Colors.primary, fontSize: 10, fontWeight: '700' }}>🐰 Bunnie</Text>
              </View>
            </View>
            <Text style={[Typography.bodyLarge, { color: Colors.onBackground, lineHeight: 26 }]}>
              {summary.summary}
            </Text>
          </SenseCard>

          {/* Highlights */}
          <View>
            <Text style={[Typography.titleMedium, { color: Colors.onBackground, marginBottom: Spacing.sm }]}>
              Today's Highlights
            </Text>
            {(summary.highlights ?? []).map((h, i) => (
              <SenseCard key={i} variant="elevated" padding="sm" style={{ marginBottom: Spacing.xs }}>
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: Spacing.sm }}>
                  <Text style={{ fontSize: 20 }}>✨</Text>
                  <Text style={[Typography.bodyMedium, { color: Colors.onBackground, flex: 1 }]}>{h}</Text>
                </View>
              </SenseCard>
            ))}
          </View>

          {/* Live Stats */}
          <View style={{ flexDirection: 'row', gap: Spacing.sm }}>
            {[
              { emoji: '💬', label: 'Conversations', value: state.user.totalConversations },
              { emoji: '👂', label: 'Sound Alerts',  value: state.soundAlerts.length },
              { emoji: '🏆', label: 'Milestones',    value: state.user.milestones.length },
              { emoji: '⚡', label: 'XP',            value: state.user.xpPoints },
            ].map(stat => (
              <SenseCard key={stat.label} variant="elevated" padding="sm" style={{ flex: 1, alignItems: 'center' }}>
                <Text style={{ fontSize: 22 }}>{stat.emoji}</Text>
                <Text style={[Typography.headlineSmall, { color: Colors.primary }]}>{stat.value}</Text>
                <Text style={[Typography.labelSmall, { color: Colors.subtitle, textAlign: 'center' }]}>{stat.label}</Text>
              </SenseCard>
            ))}
          </View>

          {/* Mood */}
          <SenseCard
            variant={summary.mood === 'positive' ? 'success' : summary.mood === 'needs_attention' ? 'danger' : 'outlined'}
            padding="md"
          >
            <View style={{ flexDirection: 'row', alignItems: 'center', gap: Spacing.sm }}>
              <Text style={{ fontSize: 32 }}>
                {summary.mood === 'positive' ? '😊' : summary.mood === 'needs_attention' ? '😟' : '😐'}
              </Text>
              <View>
                <Text style={[Typography.titleSmall, { color: Colors.onBackground }]}>Overall Mood</Text>
                <Text style={[Typography.bodyMedium, { color: Colors.onSurfaceVariant }]}>
                  {summary.mood === 'positive'
                    ? 'Positive and thriving'
                    : summary.mood === 'needs_attention'
                    ? 'May need extra support today'
                    : 'Neutral — normal day'}
                </Text>
              </View>
            </View>
          </SenseCard>

          {/* Caregiver tip from Nova */}
          {summary.tip && (
            <SenseCard variant="tonal" padding="md">
              <Text style={[Typography.labelSmall, { color: Colors.primary, marginBottom: 4 }]}>💡 NOVA TIP FOR TODAY</Text>
              <Text style={[Typography.bodyMedium, { color: Colors.onBackground }]}>{summary.tip}</Text>
            </SenseCard>
          )}

        </ScrollView>
      )}

      {/* Polly MP3 Player */}
      {mp3Uri && (
        <Video
          source={{ uri: mp3Uri }}
          audioOnly={true}
          paused={false}
          repeat={false}
          volume={1.0}
          style={{ width: 0, height: 0 }}
          onLoad={() => console.log('[Video] Polly playing')}
          onEnd={() => {
            setMp3Uri(null);
            
          }}
          onError={() => setMp3Uri(null)}
        />
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  header:      { flexDirection: 'row', alignItems: 'center', paddingHorizontal: Spacing.md, paddingTop: 56, paddingBottom: Spacing.lg, gap: Spacing.sm },
  back:        { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  refreshBtn:  { marginLeft: 'auto', width: 40, height: 40, backgroundColor: 'rgba(255,255,255,0.2)', borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  scoreCircle: { width: 140, height: 140, borderRadius: 70, borderWidth: 6, alignItems: 'center', justifyContent: 'center', ...Shadow.lg },
  novaTag:     { backgroundColor: Colors.primaryContainer, borderRadius: Radius.full, paddingHorizontal: 8, paddingVertical: 2 },
});
